### ISSUE TITLE
Multi press

### ISSUE THREAD

**Issue by ianphillpott** [LightwaveSmartHome/homeassistant-lightwave-smart#18]
I don't know if I'm just being exceptionally dumb, but I can't for the life of me get the UI button events to work!!! It's doing my nut as probably something simple.

Looking at the example, The When is "When X Smart Switch changes state or any attributes" I can add. But the And If "Confirm Event type of X Smart Switch is Short.2" - I just can't find this anywhere!! 

I've tried listening for lightwave_smart.click events as well and seems nothing comes throught.

What am I doing wrong??

Using Lightwave Smart custom component v 3.5.31

Please help my idocy!!

**Comment by nicky2702** [comment]
this is how it looks on mine, they work well! 
<img width="1092" alt="image" src="https://github.com/user-attachments/assets/be57b073-283f-4425-9790-7b52a7584ef3">

**Comment by othorp** [comment]
Agree - I think the readme could be improved to state that the relevant event entity to check for the event type will by default be named "X Smart Switch Pair" where X is device name.  A yaml version of a working automation in my case:

```
alias: "Radiator: Turn On"
description: Turn on radiator with triple press on bathroom light up button
triggers:
  - trigger: state
    entity_id:
      - light.bathroom_switch
conditions:
  - condition: state
    entity_id: event.bathroom_smart_switch_pair
    attribute: event_type
    state: Up.Short.3
actions:
  - target:
      entity_id: switch.radiator
    data: {}
    action: switch.turn_on
mode: single
```
