### ISSUE TITLE
Duplicate Multi-Press on slave switch when not pressed

### ISSUE THREAD

**Issue by RGarrett93** [LightwaveSmartHome/homeassistant-lightwave-smart#3]
I've migrated over to your official integration but unfortunately my automations (Node Red) for monitoring event type Multi-Press `lightwave_smart.click` no longer works like previously.
When I multi-press on a switch that has a slave linked it now triggers a duplicate event on the linked switch even though that button wasn't pressed for Multi-Press, it also occurs vice versa if I do the same on the slave, it triggers a duplicate multi-press event on the master switch even though it wasnt pressed.

```
event_type: lightwave_smart.click
data:
  entity_id: light.dining_room_lights_3_v2
  code: 4354
origin: LOCAL
time_fired: "2023-12-19T10:44:29.508363+00:00"
context:
  id: 01HJ0TTN6412G50EC4C6Q6J8ED
  parent_id: null
  user_id: null
```

```
event_type: lightwave_smart.click
data:
  entity_id: light.kitchen_lights_v2
  code: 4354
origin: LOCAL
time_fired: "2023-12-19T10:44:29.456326+00:00"
context:
  id: 01HJ0TTN4G9EV5DGTGVM2X2499
  parent_id: null
  user_id: null

```
